site_name: Email Application Docs
site_description: SAP CAP and Fiori Elements Documentation
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/akhsinak/localemailApp2

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: 日本語
          build: true
          site_name: ローカルメールアプリケーション
          site_dir: site/ja

nav:
  - Home: INDEX.md
  - Documentation:
    - Introduction: README.md
    - Project Structure: project-structure.md
    - Database Layer: database-layer.md
    - Service Layer: service-layer.md
    - UI Layer: ui-layer.md
    - Configuration Files: configuration-files.md
    - Security: security.md
    - Deployment: deployment.md
    - Commands: Commands.md
    - File Reference: file-reference.md
    - Glossary: glossary.md
    - Add-tile-Build-Work-Zone: how-to-add-tile-build-work-zone.md
  - S/4HANA Changes:
    - Sales Order DPC Ext Changes: 'changes in s4hana/sales_order_dpc_ext_changes.html'
  - 9020 Changes:
    - Glossary: glossary.md
    - Connect to Email App Hana cloud: 'changes in 9020 app to suuport mutiple emails\connect to email hana cloud.html'
    - Send Emails to S/4HANA local dev: 'changes in 9020 app to suuport mutiple emails\Send emails to s4hana_in local dev mode.html'
    - Send Emails to S/4HANA (deployed version): 'changes in 9020 app to suuport mutiple emails\send emails to s4hana_ after deploy.html'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
